"""""""""""""""""""""""""""""""
"""""        Vimrc       """"""
"""""  Marcus Granström  """""" 
"""""""""""""""""""""""""""""""
" Editor
packadd! dracula
colorscheme dracula
set relativenumber
set colorcolumn=80
set cursorline
set splitbelow
set splitright
set showmatch

" Editor remappings
inoremap jj <ESC>
" Window movement
noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l
" Enable mouse
set mouse=a
" Clipboard
" TODO

"  Indentation
set expandtab       " enter spaces when tab is pressed
set textwidth=120   " break lines when line length increases
set tabstop=4       " use 4 spaces to represent tab
set softtabstop=4
set shiftwidth=4    " number of spaces to use for auto indent
filetype indent on

" make backspaces more powerfull
set backspace=indent,eol,start
au BufNewFile,BufRead *.py
    \ set expandtab       |" replace tabs with spaces
    \ set autoindent      |" copy indent when starting a new line
    \ set tabstop=4
    \ set softtabstop=4
    \ set shiftwidth=4

" Find stuff
" FZF fuzzy finder
" Install from git: 
" git submodule add --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
" ~/.fzf/install
set runtimepath+=~/.vim/plugins/fzf
set runtimepath+=~/.vim/plugins/fzf.vim
nnoremap <C-p> :Files<Cr> " Local search
nnoremap <C-g> :Files ~<Cr> " Search in home
nnoremap <C-f> :Rg<Cr> " Ripgrep

" Install jedi:
" sudo apt-get install vim-python-jedi
" vim-addons install python-jedi 

packloadall
silent! helptags ALL
